name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'

jobs:
  backend:
    name: Backend CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies for backend
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Deploy backend to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
